#!/usr/bin/env python3
"""
Lead Enrichment Service
Researches and enriches leads for businesses
"""

import json
import os
import subprocess
from datetime import datetime

# Configuration
OUTPUT_DIR = "/Users/g0atface/clawd/bots/lead-enrichment"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def search_company(company_name):
    """Research a company"""
    query = f"{company_name} company about services"
    cmd = f'cd ~/clawd/skills/reddit && node scripts/reddit.mjs search all "{query}" --limit 5'
    
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
        if result.stdout:
            return json.loads(result.stdout)
    except:
        pass
    return []

def generate_lead_brief(company_name, research_data):
    """Generate a lead brief from research"""
    brief = f"""# Lead Brief: {company_name}

**Generated:** {datetime.now().strftime('%Y-%m-%d')}

## Company Info
- Name: {company_name}
- Status: Researched

## Research Findings
"""
    for item in research_data[:3]:
        brief += f"- {item.get('title', 'N/A')}\n"
    
    brief += f"""
## Potential Services
- Content marketing
- Lead generation
- Automation consulting

## Next Steps
- [ ] Verify company exists
- [ ] Find decision maker
- [ ] Prepare pitch

---
*Generated by g0atbot*
"""
    return brief

def main():
    print("🎯 Lead Enrichment Service")
    print("=" * 40)
    
    # Demo: Research some companies
    companies = [
        "small marketing agency",
        "local restaurant",
        "ecommerce store"
    ]
    
    for company in companies:
        print(f"\nResearching: {company}")
        results = search_company(company)
        
        brief = generate_lead_brief(company, results)
        
        filename = f"{OUTPUT_DIR}/{company.replace(' ', '-')}.md"
        with open(filename, "w") as f:
            f.write(brief)
        
        print(f"  ✅ Saved to {filename}")

if __name__ == "__main__":
    main()
